spring.application.name=SistemaEstoque

# 1. Configuração do MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_estoque?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=ruan2004

# 2. Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Desativar o Console do H2 (Para evitar o erro que deu)
spring.h2.console.enabled=false